### ISSUE TITLE
We kinda need to start the heuristic...

### ISSUE THREAD

**Issue by tgautz** [tbixler1/COSC-481W-Project-Scheduling-#11]
Here's some (very) rough starter code for the constructor for the heuristic me thinks.
I would like some feedback on what you guys think.  With just some getters and a few new variable declarations, I was able to get the frontScreen object to be able to pass these parameters.

public Heuristic(ArrayList<TutorInfo> tutorList, Schedule openSchedule, Rules rules)
{
    //how to get information out of a tutor (out of a TutorInfo)
    TutorInfo firstTutor = tutorList.get(0);
    Object[] firstTutorStats = firstTutor.getAllInfo();
            /**Code for what getAllInfo looks like

```
        Object[] retVal = new Object[3];
        String[] strings = {name, EID, phone, email, emergencyContactName, emergencyContactPhone, emergencyContactRelation, major};
        retVal[0] = strings;

        //i = Sunday, Monday, Tuesday, ... , Saturday
        //j = midnight-to-1am, 1am-to-2am, 2am-3am, ... , 11pm-to-midnight
        int[] ints = new int[175];
        for(int i=0; i<7; i++)
                for(int j=0; j<24; j++)
                        ints[i*24+j] = availability[i][j];
        ints[168] = position;
        ints[169] = minHours;
        ints[170] = maxHours;
        ints[171] = workStudyHours;
        ints[172] = coordinatorMin;
        ints[173] = coordinatorMax;
        ints[174] = contractHours;
        retVal[1] = ints;

        //classes.length = 29
        boolean[] bools = new boolean[classes.length+1];
        bools[0] = isLead;
        for(int i=1; i<=classes.length; i++)
                bools[i] = classes[i-1];
        retVal[2] = bools;
        return retVal;
        **/


//length = 8
//int numOfActualNewClasses = Integer.parseInt(newClasses[0]);
//gives the names of the new classes
//indicies 1-7 correspond to the last 7 classes of bools[] from above
//
String[] newClasses = rules.getNewClassNames();
```

}

**Comment by andrewsbryanc** [comment]
Looks pretty good, I think the next part will need to be using the lab schedule to over schedule the lab with all employees that prefer those hours; and if the hours aren't filled, use availability hours to finish filling the schedule.  If at that point we don't have enough for a spot, return a warning or failure that we literally cannot fill that schedule with the tutor list given.  So I'm going to break this down into multiple parts for priority listing.

1) Fill each hour with all tutors/GA's preferred hours, then do it for proctors separately.
2) If an hour is not filled to quota, fill it with all available hours for tutors/GA's or proctors, respectively.  
2a) There is an issue with logic here, we need GA's to be filled to their mark, so I'm thinking we need to do two runs of 1) and 2), starting with GA's, then doing a second pass for tutors.  Let me know what you guys think of this idea.  The current flaw I see with the plan I have right now is that if a GA were to only put available hours and no preferred, and all hours are filled by tutors who put those hours as preferred, a GA won't be scheduled the number of hours needed for their contract work.
2b) Another idea is to fill GA preferred, and after GA preferred are filled, if GA preferred hours isn't equal to their contract hours, fill in GA available hours to get in their hours.  After this, we then check to see if GA's have number of contract hours, and if not, then return a warning or error because we can't schedule a GA for his number of contract hours.  After that, apply tutor preferred and available hours.
Let me know what you guys think of this idea!

**Comment by tgautz** [comment]
1. Fill everyone where the person != unavailable && lab==open
   1a. for all time slots, if open lab slot's minTutor > people scheduled
       in this time slot, issue error in error log and fill with "Need Person" tutors
   1b. if any GA has scheduled hours < their contracted hours, issue error in error
       log, display error log, and terminate the heuristic (exit(1))
2. for all time slots {
       while(this time slot is over scheduled) {
           order GAs by max(scheduled - contract)
               cut GA available until GA scheduled hours == contracted hours
               cut GA preferred until GA scheduled hours == contracted hours
           order GAs by max(scheduled - coordinator max hours)
               cut Tutor available until tutor scheduled hours == coordinator min hours
               cut Tutor preferred until tutor scheduled hours == coordinator min hours
       }
       if(this time slot is still over scheduled)
           issue error in error log("time slot X is over scheduled, tutors all at coord min,
               GAs at contract, tutor Y is below coord min"), keep running heuristic
               (tutor Y = tutor with largest scheduled hours)
   }

[heuristic prottype.txt](https://github.com/tbixler1/COSC-481W-Project-Scheduling-/files/28265/heuristic.prottype.txt)

**Comment by tgautz** [comment]
Bryan, have you started the heuristic?  If yes and if there's nothing left that you need from this issue, please close this issue.
